#!/bin/bash



# Set time to locale, important for dual boot machines
timedatectl set-local-rtc 1 --adjust-system-clock

# A little better dnf 
if [[ -f /etc/dnf/dnf.conf ]]; then

	cat << EOF >> /etc/dnf/dnf.conf 
fastestmirror=True
max_parallel_downloads=5
defaultyes=True
keepcache=True
EOF

fi

# Enable access to the free and the non free repository
sudo dnf install "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"

# AppStream Metadata for Gnome Software
sudo dnf groupupdate core

# Sethostname to something nicer
sudo hostnamectl set-hostname mauwt

