#!/bin/bash

CONFIG_HOME=$HOME/.config
DF=$HOME/.dotfiles
DF_LOCAL_BIN=$HOME/.dotfiles/.local/bin


create_symlink(){
	
	if [[ -f $2/$1 ]]; then
		echo "Found existing file $2/$1 creating backup on $2/$1.bak"
		mv $2/$1  $2/$1.bak
	fi
	
	echo "Con el siguiente comando"
	echo "ln -sf $HOME/.dotfiles/$1 $2/$1"

	sudo ln -sf $HOME/.dotfiles/$1 $2/$1
}



sudo dnf install -y bspwm sxhkd polybar picom rofi dunst feh alacritty xrandr vim

if [[ $? -ne 0 ]]; then
    echo "Error installing dependencies. Exiting."
    exit 1
fi


if ! [[ -d $CONFIG_HOME ]]; then
	mkdir $CONFIG_HOME
fi


files=(".bashrc" ".bash_profile" ".bash_logout" ".Xresources")
directories=("alacritty" "bspwm" "dunst" "picom" "polybar" "rofi" "sxhkd")


# Create links for configuration directories like:
# ~/.config/{dependency} -> ~/.dotfiles/{dependency}/

for d in "${directories[@]}"; do
	echo "creando symlink para la carpeta $d"
	create_symlink $d $CONFIG_HOME
done


#Create links for configuration files
for f in "${files[@]}"; do
	echo "creando symlink para el archivo $f"
	create_symlink $f $HOME
done



export PATH=$PATH:"$DF_LOCAL_BIN"
