#!/bin/bash

#Creates a file for Touchpad info configuration and writes the right options for
#	- Tap to click
# 	- Enabale two and three finger tap
#	- Disable Natural Scrolling

sudo touch /etc/X11/xorg.conf.d/90-touchpad.conf

sudo tee <<'EOF' /etc/X11/xorg.conf.d/90-touchpad.conf 1> /dev/null
Section "InputClass"
        Identifier "touchpad"
        MatchIsTouchpad "on"
        Driver "libinput"
        Option 	"Tapping" "on"
	Option 	"NaturalScrolling" "off"
        Option 	"ScrollMethod" "twofinger"
        Option 	"TappingButtonMap" "lrm"
EndSection

EOF
